#Ref https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/

# Creating service using loadbalncer so that we can access our webpage from internet
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer # using loadbalancer for public access
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: nginx

#Creating statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: nginx
          imagePullPolicy: Never
          image: yougovnginx:latest # image name
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "my-storage-class" # Please mention storageClassName for claiming volume.
        resources:
          requests:
            storage: 1Gi
